server:
  host: "localhost"
  port: 3000
  
database:
  host: "localhost"
  port: 5432
  name: "social_security_db"
  user: "postgres"
  password: "your_password"
  sslmode: "disable"
  max_open_conns: 20
  max_idle_conns: 5
  conn_max_lifetime: "1h"

logger:
  level: "info"
  format: "json" 